name: Build and push Docker image

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Specify the redlib version (e.g., v0.35.1)'
        required: true
        default: 'v0.35.1'  # Default version if not specified

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download redlib binary and set permissions
        run: |
          wget "https://github.com/redlib-org/redlib/releases/download/${{ github.event.inputs.target }}/redlib"
          chmod +x redlib

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.target }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
